#!/usr/bin/env ruby

class Yes
  def initialize
    @argv = ARGV
  end

  def yes
    while(true) do
      if(@argv.any?)
        puts @argv
      else
        puts 'y'
      end
    end
  end
end

yes = Yes.new
yes.yes
